name: MCP-Eval CI

on:
  push:
    branches: [ main, master, trunk ]
  workflow_dispatch:

# Cancel redundant runs on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-mcpeval:
    uses: ./.github/workflows/mcpeval-reusable.yml
    secrets: inherit
  consume:
    runs-on: ubuntu-latest
    needs: call-mcpeval
    steps:
      - run: |
          echo "HTML report:  ${{ needs.call-mcpeval.outputs.html }}"
          echo "JSON report:  ${{ needs.call-mcpeval.outputs.json }}"
          echo "Markdown:     ${{ needs.call-mcpeval.outputs.md }}"