name: MCP Eval Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:  # manual run button

jobs:
  tests:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run MCP-Eval
        id: mcpeval
        uses: StreetLamb/mcp-eval/.github/actions/mcp-eval/run@v0.1.0
        with:
          python-version: '3.11'
          tests: tests/
          run-args: '-v --max-concurrency 4'
          pr-comment: 'true'
          set-summary: 'true'
          upload-artifacts: 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Generate badges
        id: badges
        uses: StreetLamb/mcp-eval/.github/actions/mcp-eval/badges@v0.1.0
        with:
          report-path: ${{ steps.mcpeval.outputs.results-json-path }}
          output-dir: mcpeval-reports/badges
          upload-artifacts: 'true'
          artifact-name: mcpeval-badges