name: MCP Eval Main Branch
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # manual run button

jobs:
  tests:
    permissions:
      contents: write  # Need write access to commit badges
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run MCP-Eval
        id: mcpeval
        uses: StreetLamb/mcp-eval/.github/actions/mcp-eval/run@v0.1.0
        with:
          python-version: '3.11'
          tests: tests/
          run-args: '-v --max-concurrency 4'
          pr-comment: 'false'  # No PR comments needed for main branch
          set-summary: 'true'
          upload-artifacts: 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Generate badges
        uses: ./.github/actions/mcp-eval/badges
        with:
          report-path: ${{ steps.mcpeval.outputs.results-json-path }}
          output-dir: badges
          format: 'both'  # Generate both SVG and JSON endpoint files
          upload-artifacts: 'true'  # Upload artifacts for GitHub Pages deployment